### ISSUE TITLE
Visual Studio 2015 Crash!

### ISSUE THREAD

**Issue by floydchenv** [onlyutkarsh/AppVeyorExtension#1]
When I drag the plug-in window,Visual Studio 2015 Crash...
But I like this plugin very much, hope to continue to update!

**Comment by floydchenv** [comment]
Constructs an exception was encountered when the contents of the frame. This information is also logged in “C:\Users\Floyd\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml”。

Exception details:
System.UnauthorizedAccessException: Deny access to 
(exception from HRESULT:0x80070005 (E_ACCESSDENIED))
   in Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
   in Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()
   in Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()

**Comment by tarunaroraonline** [comment]
Hello, 

Thank you for the feedback, really appreciate you trying the extension and raising the issue here. 

#### Just to confirm -

---
- Do you get this exception when you undock the AppVeyor tool window in Visual Studio 2015? 
- What Visual Studio SKU are you on?

@onlyutkarsh and I will look at it further once you provide us the above requested information. 

Thanks

**Comment by floydchenv** [comment]
- When I set up the API Token, I try to dock the AppVeyor tool window in Visual Studio 2015
- I'm using the  Enterprise Edition

**Comment by PINK-FL0YD** [comment]
- When I set up the API token, I try to dock the AppVeyor tool window in Visual Studio 2015
- I'm using the Enterprise Edition

**Comment by onlyutkarsh** [comment]
@PINK-FL0YD thanks, one more quick question to help us finding the root cause, once you add the API token, can you see your repos (without docking tool window)? Also, rest of the functionalities of extension work fine?

**Comment by floydchenv** [comment]
Yes,I can see that

**Comment by floydchenv** [comment]
![2](https://cloud.githubusercontent.com/assets/7371136/10927170/7ef9e9b0-82d8-11e5-9ac2-36252303b6c3.gif)

**Comment by onlyutkarsh** [comment]
@PINK-FL0YD thanks for sharing this gif, it clears our doubt. I see that you are actually clicking the options icon on the toolbar (and not dragging the window) isnt it?

**Comment by floydchenv** [comment]
After several attempts, I found that when I set up the API token, and then open the plug-in window, no matter what I do, VS2015 will crash after it finishes loading the content.First I found the problem is in the process of dragging, misleading tips for you, I'm sorry for that.   :)

**Comment by onlyutkarsh** [comment]
@PINK-FL0YD I tried replicating the issue in couple of machines, but I am not able to replicate this error unfortunately. 
- Is it possible for you to send the activity log? 
- Can you confirm that uninstalling  this extension resolves the VS crash? 
- Also, which OS are you using?

**Comment by floydchenv** [comment]
I am using the Windows10-10586, I tried on both VS2013 and VS2015 on two computers, 
the VisualStudio always be crashed.
I went into safe mode, then uninstall this plug-in, VS returning to normal.
Below are the activity log:

**Comment by floydchenv** [comment]
https://www.dropbox.com/sh/3kslp4eesm2n046/AAC9sdtOte7OBEOiG3w467x3a?dl=0
